# Generated by Django 4.1.2 on 2022-10-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PixivId', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=30)),
                ('Nick', models.CharField(max_length=30)),
            ],
        ),
    ]
